name: CI testes automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executar os testes com pytest
      - name: Executar todos os testes
        run: |
          pytest -s
    